### ISSUE TITLE
managed localize resource with `lang` attribute

### ISSUE THREAD

**Issue by kazupon** [kazupon/vue-i18n-loader#11]
related from https://github.com/kazupon/vue-i18n/issues/249

e.g.
```html
// someFile.vue
<template>
  ...
</template>

<i18n lang="zh-CN" src='./zh-CN.json'></i18n>
<i18n lang="zh-TW" src='./zh-TW.json'></i18n>
<i18n lang="en" src='./en.json'></i18n>

<script>
export default {
  ...
}
</script>
```

**Comment by antfu** [comment]
@kazupon Hi! I would think this approach is kinda of confusing from the original vue sfc. `lang` attr is to specify the preprocessor programming language in `template` `script` and `style`. I would suggest to use another attr name instead of `lang` and leave lang for specify the locale preprocessor.

**Comment by kazupon** [comment]
@antfu 
Thank you for feedback!

It's no problem. 😉 
I've implemented with `locale` attr.
https://github.com/kazupon/vue-i18n-loader/blob/dev/src/index.ts#L31
