### ISSUE TITLE
Hot-module-replacement support

### ISSUE THREAD

**Issue by mcongy** [kazupon/vue-i18n-loader#7]
Hello,

Is it possible to properly HMR `<i18n>` tags?
It doesn't work for me.

HMR does work properly for my .vue files (it correctly picks up changes from templates/scripts..).
It does see changes coming from `<i18n>` tags and I do see HMR output in console. Problem is, it doesn't pick up the changes.

I'm using webpack.HotModuleReplacementPlugin, and webpackDevServer with `{ hot: true }` option

Is it just not implemented, or do I have to do some additional setup to make it work?

Thanks!

PS. Thanks for the good work with this loader and vue-i18n. I really like it!

**Comment by kazupon** [comment]
sorry, vue-i18n-loader cannot support HMR yet.
I'll plan to supporting it. 😉

**Comment by suil** [comment]
any timeline about when it will be supported?

**Comment by Napzu** [comment]
Yeah I also like to know when HMR for <i18n> would land?

**Comment by Twinpix** [comment]
+1, it would be great feature

**Comment by mario-d-s** [comment]
Hey, I'm using this loader for `i18n` tag support and HMR doesn't work for me... I'm on the latest release (0.3.0).

Note: I'm using https://github.com/panter/vue-i18next instead of https://github.com/kazupon/vue-i18n but I don't think that could make a difference (neither project knows or cares about `i18n` tags in `.vue` components)

**Comment by tmcdos** [comment]
It's 2021 and this loader still does not support HMR - 5 years ...
